### ISSUE TITLE
Unable to use MSR-2 as BLE proxy - Please remove power save mode in the yaml

### ISSUE THREAD

**Issue by bharvey88** [ApolloAutomation/MSR-2#15]
https://github.com/ApolloAutomation/MSR-2/blob/main/Integrations/ESPHome/MSR-2.yaml#L109
![image](https://github.com/user-attachments/assets/95eae698-2bef-4a64-a116-4341971dd4ca)

Unable to use MSR-2 as BLE proxy - Please remove power save mode in the yaml

**Comment by foXaCe** [comment]
hello, same problem for me

**Comment by TrevorSchirmer** [comment]
@bharvey88 @foXaCe We created specific BLE versions of our firmware so we can keep things like power_save_mode in the production firmware but if people want to add BLE proxy they would switch to: MSR-2_BLE.yaml in ESPHome addon.

Have you guys tried switching to that? Just replace MSR-2.yaml with MSR02_BLE.yaml in ESPHome addon

**Comment by bharvey88** [comment]
trevor this does not work because of the error above- the msr-2 ble yaml would need to include a "!remove" for the wifi power save mode.

**Comment by foXaCe** [comment]
work for me thanks you
